server:
  port: 9090

spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: ${AWS_RDS_URL}/nasdak_schema
    username: ${AWS_RDS_USER}
    password: ${AWS_RDS_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
#        highlight_sql: true
#        use_sql_comments: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    p6spy: info
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace
#            BasicBinder: trace

#file: # ??? ??? ??? ?? ??
#  name: app.log # ?? ???
#  path: logs # ?? ?? ??
#  max-history: 7 # ??? ?? ??? ?? ??




##  file: # ??? ??? ??? ?? ??
##    name: app.log # ?? ???
##    path: logs # ?? ?? ??
##    max-history: 7 # ??? ?? ??? ?? ??
##

path:
  context-root : ${user.dir}
  front: http://localhost:3000
  back: http://localhost:9090
upload:
  file:
#    path: D:/Devspace/uploadFile
    path: ${user.dir}/src/main/front/public/image
    profile : ${user.dir}/src/main/front/public/image/userProfile
download:
  file:
    profile: /image/userProfile/