server:
  port: 5050

spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    #      url: jdbc:p6spy:h2:tcp://localhost/./nasdak
    #      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #      username: nasdak
    #      password: nasdak12@
    url: jdbc:mysql://localhost:3306/nasdak
    username: nasdak
    password: nasdak12@
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        format_sql: true
#        highlight_sql: true
#        use_sql_comments: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
#    root: off
    p6spy: info
#    org.nasdakgo.nasdak.*: warn
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace
#            BasicBinder: trace

#file: # ??? ??? ??? ?? ??
#  name: app.log # ?? ???
#  path: logs # ?? ?? ??
#  max-history: 7 # ??? ?? ??? ?? ??




##  file: # ??? ??? ??? ?? ??
##    name: app.log # ?? ???
##    path: logs # ?? ?? ??
##    max-history: 7 # ??? ?? ??? ?? ??
##

path:
  context-root : ${user.dir}
  front: http://localhost:3000
  back: http://localhost:9090
upload:
  file:
#    path: D:/Devspace/uploadFile
    path: ${user.dir}/src/main/front/public/image
    profile : ${user.dir}/src/main/front/public/image/userProfile
download:
  file:
    profile: /image/userProfile/